//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_3.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_3.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string ABJVCancel {
            get {
                return ResourceManager.GetString("ABJVCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string ABJVComplete {
            get {
                return ResourceManager.GetString("ABJVComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination path.
        /// </summary>
        public static string ABJVDest {
            get {
                return ResourceManager.GetString("ABJVDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string ABJVDiff {
            get {
                return ResourceManager.GetString("ABJVDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string ABJVExe {
            get {
                return ResourceManager.GetString("ABJVExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name is already used..
        /// </summary>
        public static string ABJVMNameError {
            get {
                return ResourceManager.GetString("ABJVMNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an existing path..
        /// </summary>
        public static string ABJVMPathError {
            get {
                return ResourceManager.GetString("ABJVMPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a save type..
        /// </summary>
        public static string ABJVMSaveTypeError {
            get {
                return ResourceManager.GetString("ABJVMSaveTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string ABJVName {
            get {
                return ResourceManager.GetString("ABJVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save type.
        /// </summary>
        public static string ABJVSaveType {
            get {
                return ResourceManager.GetString("ABJVSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source path.
        /// </summary>
        public static string ABJVSource {
            get {
                return ResourceManager.GetString("ABJVSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a Backup Job.
        /// </summary>
        public static string ABJVTitle {
            get {
                return ResourceManager.GetString("ABJVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm the deletion of this Backup Job:.
        /// </summary>
        public static string DBJCBoxText {
            get {
                return ResourceManager.GetString("DBJCBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Backup Job.
        /// </summary>
        public static string DBJCBoxTitle {
            get {
                return ResourceManager.GetString("DBJCBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save State.
        /// </summary>
        public static string EVMBoxTitle {
            get {
                return ResourceManager.GetString("EVMBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save is complete..
        /// </summary>
        public static string EVMSaveComplete {
            get {
                return ResourceManager.GetString("EVMSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files are being copied ....
        /// </summary>
        public static string EVText {
            get {
                return ResourceManager.GetString("EVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing Backup Job.
        /// </summary>
        public static string EVTitle {
            get {
                return ResourceManager.GetString("EVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string MBJAdd {
            get {
                return ResourceManager.GetString("MBJAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string MBJDelete {
            get {
                return ResourceManager.GetString("MBJDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute.
        /// </summary>
        public static string MBJExecute {
            get {
                return ResourceManager.GetString("MBJExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination Path.
        /// </summary>
        public static string MBJListDestination {
            get {
                return ResourceManager.GetString("MBJListDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string MBJListName {
            get {
                return ResourceManager.GetString("MBJListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Type.
        /// </summary>
        public static string MBJListSave {
            get {
                return ResourceManager.GetString("MBJListSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Path.
        /// </summary>
        public static string MBJListSource {
            get {
                return ResourceManager.GetString("MBJListSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your Backup Jobs.
        /// </summary>
        public static string MBJTitle {
            get {
                return ResourceManager.GetString("MBJTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a 
        ///Backup Job.
        /// </summary>
        public static string MMCreate {
            get {
                return ResourceManager.GetString("MMCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your
        /// Backup Jobs.
        /// </summary>
        public static string MMManage {
            get {
                return ResourceManager.GetString("MMManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MMSettings {
            get {
                return ResourceManager.GetString("MMSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave.
        /// </summary>
        public static string MMTitle {
            get {
                return ResourceManager.GetString("MMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving and crypting software by Thomas, Yanis, Mehdi and Antoine.
        /// </summary>
        public static string MMTitle2 {
            get {
                return ResourceManager.GetString("MMTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application is now in English..
        /// </summary>
        public static string SLCBoxText {
            get {
                return ResourceManager.GetString("SLCBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to cancel the backup job?.
        /// </summary>
        public static string SSCBoxText {
            get {
                return ResourceManager.GetString("SSCBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel Save.
        /// </summary>
        public static string SSCBoxTitle {
            get {
                return ResourceManager.GetString("SSCBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your log file is now in json..
        /// </summary>
        public static string STLCBoxJson {
            get {
                return ResourceManager.GetString("STLCBoxJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your log file is now in xml..
        /// </summary>
        public static string STLCBoxXml {
            get {
                return ResourceManager.GetString("STLCBoxXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string SVAdd {
            get {
                return ResourceManager.GetString("SVAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string SVConfirm {
            get {
                return ResourceManager.GetString("SVConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert Log file.
        /// </summary>
        public static string SVConvert {
            get {
                return ResourceManager.GetString("SVConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions to encrypt.
        /// </summary>
        public static string SVExt1 {
            get {
                return ResourceManager.GetString("SVExt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (.txt, .pdf, .doc, .mp4 ...).
        /// </summary>
        public static string SVExt2 {
            get {
                return ResourceManager.GetString("SVExt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File priority.
        /// </summary>
        public static string SVFilePriority1 {
            get {
                return ResourceManager.GetString("SVFilePriority1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (.txt, .pdf, .doc, .mp4 ...).
        /// </summary>
        public static string SVFilePriority2 {
            get {
                return ResourceManager.GetString("SVFilePriority2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job App.
        /// </summary>
        public static string SVJobApp1 {
            get {
                return ResourceManager.GetString("SVJobApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (notepad, iexplorer, firefox ...).
        /// </summary>
        public static string SVJobApp2 {
            get {
                return ResourceManager.GetString("SVJobApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        public static string SVJson {
            get {
                return ResourceManager.GetString("SVJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string SVLang {
            get {
                return ResourceManager.GetString("SVLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string SVLangen {
            get {
                return ResourceManager.GetString("SVLangen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string SVLangfr {
            get {
                return ResourceManager.GetString("SVLangfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App job already added..
        /// </summary>
        public static string SVMAppJobError {
            get {
                return ResourceManager.GetString("SVMAppJobError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max file size.
        /// </summary>
        public static string SVMaxSize1 {
            get {
                return ResourceManager.GetString("SVMaxSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (in bytes).
        /// </summary>
        public static string SVMaxSize2 {
            get {
                return ResourceManager.GetString("SVMaxSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension already added..
        /// </summary>
        public static string SVMExtensionError {
            get {
                return ResourceManager.GetString("SVMExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of file already added..
        /// </summary>
        public static string SVMFilePriorityError {
            get {
                return ResourceManager.GetString("SVMFilePriorityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a number (bytes)..
        /// </summary>
        public static string SVMMaxFileSizeError {
            get {
                return ResourceManager.GetString("SVMMaxFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string SVRemove {
            get {
                return ResourceManager.GetString("SVRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SVTitle {
            get {
                return ResourceManager.GetString("SVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XML.
        /// </summary>
        public static string SVXML {
            get {
                return ResourceManager.GetString("SVXML", resourceCulture);
            }
        }
    }
}
